Online_insurance_underwriter/config/routes.rb
Broker::Application.routes.draw do
  resources :quotes

  resources :policies

  resources :claims

  resources :vehicles

  resources :customers do
    resource :vehicle
    resources :claims
    resource :policy
    resource :quote
  end

root 'customers#index'
match "quote/:email/:identifier" => "quotes#get_customer_details", :constraints => { :email => /.+@.+\..*/ }, via: [:get]

  

end

Online_insurance_underwriter/app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :customer
end

Online_insurance_underwriter/app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  require 'securerandom'
  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new(:customer_id => params[:customer_id])
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json

  def create
    @quote = Quote.new(quote_params)
    @quote.customer_id = params[:customer_id]
    @quote.amount = rand(100..1000)
      #The identifier is created using a string random and the customer ID
    @quote.identifier = "#{@quote.customer_id}#{SecureRandom.hex(2)}"


    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render action: 'show', status: :created, location: @quote }
      else
        format.html { render action: 'new' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end


  def get_customer_details

    @quote = Quote.find_by_identifier(params[:identifier])
    @customer = Customer.find(@quote.customer_id)
    respond_to  do |format|
      if (@customer.email == params[:email])
       format.json {render action: 'show',status: :created, location: @customer }
      end
    end


  end
  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
     @quote = Quote.find_by_customer_id(params[:customer_id])
      #@customer = Customer.find(params[:customer_id])
      #@quote = @customer.quote
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:customer_id, :amount, :identifier)
    end
end

Online_insurance_underwriter/app/helpers/quotes_helper.rb
module QuotesHelper
end

Online_insurance_underwriter/app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :identifier %><br>
    <%= f.number_field :identifier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Online_insurance_underwriter/app/views/quotes/edit.html.erb
<h1>Editing quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

Online_insurance_underwriter/app/views/quotes/index.html.erb
<h1>Listing quotes</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Identifier</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.amount %></td>
        <td><%= quote.identifier %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

Online_insurance_underwriter/app/views/quotes/new.html.erb
<h1>New quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

Online_insurance_underwriter/app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @quote.amount %>
</p>

<p>
  <strong>Identifier:</strong>
  <%= @quote.identifier %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>