Online_insurance_underwriter/config/routes.rb
Broker::Application.routes.draw do
  resources :quotes

  resources :policies

  resources :claims

  resources :vehicles

  resources :customers do
    resource :vehicle
    resources :claims
    resource :policy
    resource :quote
  end

root 'customers#index'
match "quote/:email/:identifier" => "quotes#get_customer_details", :constraints => { :email => /.+@.+\..*/ }, via: [:get]

  

end

Online_insurance_underwriter/app/models/claim.rb
class Claim < ActiveRecord::Base

  belongs_to :customer
end

Online_insurance_underwriter/app/controllers/claims_controller.rb
class ClaimsController < ApplicationController
  before_action :set_claim, only: [:show, :edit, :update, :destroy]

  # GET /claims
  # GET /claims.json
  def index
    @claims = Claim.all
  end

  # GET /claims/1
  # GET /claims/1.json
  def show
  end

  # GET /claims/new
  def new
    #@customer = Customer.find(params[:customer_id])
    #@claim = @customer.claims.create
    @claim = Claim.new(:customer_id => params[:customer_id])
  end

  # GET /claims/1/edit
  def edit
  end

  # POST /claims
  # POST /claims.json
  def create

    @claim = Claim.new(claim_params)

    respond_to do |format|
      if @claim.save
        format.html { redirect_to @claim, notice: 'Claim was successfully created.' }
        format.json { render action: 'show', status: :created, location: @claim }
      else
        format.html { render action: 'new' }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /claims/1
  # PATCH/PUT /claims/1.json
  def update
    respond_to do |format|
      if @claim.update(claim_params)
        format.html { redirect_to @claim, notice: 'Claim was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @claim.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /claims/1
  # DELETE /claims/1.json
  def destroy
    @claim.destroy
    respond_to do |format|
      format.html { redirect_to claims_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_claim
      @claim = Claim.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def claim_params
      params.require(:claim).permit(:customer_id, :date_of_incident, :value, :type_of_incident, :description)
    end
end

Online_insurance_underwriter/app/helpers/claims_helper.rb
module ClaimsHelper
end

Online_insurance_underwriter/app/views/claims/_form.html.erb
<%= form_for(@claim) do |f| %>
  <% if @claim.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@claim.errors.count, "error") %> prohibited this claim from being saved:</h2>

      <ul>
      <% @claim.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date_of_incident %><br>
    <%= f.date_select :date_of_incident %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.number_field :value %>
  </div>
  <div class="field">
    <%= f.label :type_of_incident %><br>
    <%= f.text_field :type_of_incident %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Online_insurance_underwriter/app/views/claims/edit.html.erb
<h1>Editing claim</h1>

<%= render 'form' %>

<%= link_to 'Show', @claim %> |
<%= link_to 'Back', claims_path %>

Online_insurance_underwriter/app/views/claims/index.html.erb
<h1>Listing claims</h1>

<table>
  <thead>
    <tr>
      <th>Date of incident</th>
      <th>Value</th>
      <th>Type of incident</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @claims.each do |claim| %>
      <tr>
        <td><%= claim.date_of_incident %></td>
        <td><%= claim.value %></td>
        <td><%= claim.type_of_incident %></td>
        <td><%= claim.description %></td>
        <td><%= link_to 'Show', claim %></td>
        <td><%= link_to 'Edit', edit_claim_path(claim) %></td>
        <td><%= link_to 'Destroy', claim, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Claim', new_claim_path %>

Online_insurance_underwriter/app/views/claims/new.html.erb
<h1>New claim</h1>

<%= render 'form' %>

<%= link_to 'Back', claims_path %>

Online_insurance_underwriter/app/views/claims/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date of incident:</strong>
  <%= @claim.date_of_incident %>
</p>

<p>
  <strong>Value:</strong>
  <%= @claim.value %>
</p>

<p>
  <strong>Type of incident:</strong>
  <%= @claim.type_of_incident %>
</p>

<p>
  <strong>Description:</strong>
  <%= @claim.description %>
</p>

<%= link_to 'Edit', edit_claim_path(@claim) %> |
<%= link_to 'Back', claims_path %>