Online_insurance_underwriter/config/routes.rb
Broker::Application.routes.draw do
  resources :quotes

  resources :policies

  resources :claims

  resources :vehicles

  resources :customers do
    resource :vehicle
    resources :claims
    resource :policy
    resource :quote
  end

root 'customers#index'
match "quote/:email/:identifier" => "quotes#get_customer_details", :constraints => { :email => /.+@.+\..*/ }, via: [:get]

  

end

Online_insurance_underwriter/app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  belongs_to :customer
end

Online_insurance_underwriter/app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    #@customer = Customer.find(params[:customer_id])
   # @vehicle = @customer.create_vehicle
    @vehicle = Vehicle.new(:customer_id => params[:customer_id])

  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @vehicle }
      else
        format.html { render action: 'new' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find_by_customer_id(params[:customer_id])
      #@customer = Customer.find(params[:customer_id])
      #@vehicle = @customer.vehicle
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:customer_id, :vehicle_reg, :annual_mileage, :vehicle_value, :parking_location, :policy_start_date)
    end
end

Online_insurance_underwriter/app/helpers/vehicles_helper.rb
module VehiclesHelper
end

Online_insurance_underwriter/app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vehicle_reg %><br>
    <%= f.text_field :vehicle_reg %>
  </div>
  <div class="field">
    <%= f.label :annual_mileage %><br>
    <%= f.number_field :annual_mileage %>
  </div>
  <div class="field">
    <%= f.label :vehicle_value %><br>
    <%= f.number_field :vehicle_value %>
  </div>
  <div class="field">
    <%= f.label :parking_location %><br>
    <%= f.text_field :parking_location %>
  </div>
  <div class="field">
    <%= f.label :policy_start_date %><br>
    <%= f.datetime_select(:policy_start_date, :include_blank => true) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Online_insurance_underwriter/app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

Online_insurance_underwriter/app/views/vehicles/index.html.erb
<h1>Listing vehicles</h1>

<table>
  <thead>
    <tr>
      <th>Vehicle reg</th>
      <th>Annual mileage</th>
      <th>Vehicle value</th>
      <th>Parking location</th>
      <th>Policy start date</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.vehicle_reg %></td>
        <td><%= vehicle.annual_mileage %></td>
        <td><%= vehicle.vehicle_value %></td>
        <td><%= vehicle.parking_location %></td>
        <td><%= vehicle.policy_start_date %></td>
        <td><%= link_to 'Show', vehicle %></td>
        <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
        <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vehicle', new_vehicle_path %>

Online_insurance_underwriter/app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

Online_insurance_underwriter/app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle registration:</strong>
  <%= @vehicle.vehicle_reg %>
</p>

<p>
  <strong>Annual mileage:</strong>
  <%= @vehicle.annual_mileage %>
</p>

<p>
  <strong>Vehicle value:</strong>
  <%= @vehicle.vehicle_value %>
</p>

<p>
  <strong>Parking location:</strong>
  <%= @vehicle.parking_location %>
</p>

<p>
  <strong>Policy start date:</strong>
  <%= @vehicle.policy_start_date %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>