Online_insurance_underwriter/config/routes.rb
Broker::Application.routes.draw do
  resources :quotes

  resources :policies

  resources :claims

  resources :vehicles

  resources :customers do
    resource :vehicle
    resources :claims
    resource :policy
    resource :quote
  end

root 'customers#index'
match "quote/:email/:identifier" => "quotes#get_customer_details", :constraints => { :email => /.+@.+\..*/ }, via: [:get]

  

end

Online_insurance_underwriter/app/models/policy.rb
class Policy < ActiveRecord::Base
  belongs_to :customer

end

Online_insurance_underwriter/app/controllers/policies_controller.rb
class PoliciesController < ApplicationController
  before_action :set_policy, only: [:show, :edit, :update, :destroy]

  # GET /policies
  # GET /policies.json
  def index
    @policies = Policy.all
  end

  # GET /policies/1
  # GET /policies/1.json
  def show
  end

  # GET /policies/new
  def new
   #@customer = Customer.find(params[:customer_id])
    #@policy = @customer.create_policy
    @policy = Policy.new(:customer_id => params[:customer_id])

  end

  # GET /policies/1/edit
  def edit
  end

  # POST /policies
  # POST /policies.json
  def create

    @policy = Policy.new(policy_params)

    respond_to do |format|
      if @policy.save
        format.html { redirect_to @policy, notice: 'Policy was successfully created.' }
        format.json { render action: 'show', status: :created, location: @policy }
      else
        format.html { render action: 'new' }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /policies/1
  # PATCH/PUT /policies/1.json
  def update
    respond_to do |format|
      if @policy.update(policy_params)
        format.html { redirect_to @policy, notice: 'Policy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @policy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /policies/1
  # DELETE /policies/1.json
  def destroy
    @policy.destroy
    respond_to do |format|
      format.html { redirect_to policies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_policy
      @policy = Policy.find_by_customer_id(params[:customer_id])
     # @customer = Customer.find(params[:customer_id])
      #@policy = @customer.policy
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def policy_params
      params.require(:policy).permit(:customer_id, :policy_excess, :breakdown_cover, :windscreen_repair, :windscreen_cost)
    end
end

Online_insurance_underwriter/app/helpers/policies_helper.rb
module PoliciesHelper
end

Online_insurance_underwriter/app/views/policies/_form.html.erb
<%= form_for(@policy) do |f| %>
  <% if @policy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@policy.errors.count, "error") %> prohibited this policy from being saved:</h2>

      <ul>
      <% @policy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :policy_excess %><br>
    <%= f.number_field :policy_excess %>
  </div>
  <div class="field">
    <%= f.label :breakdown_cover %><br>
    <%= f.text_field :breakdown_cover %>
  </div>
  <div class="field">
    <%= f.label :windscreen_repair %><br>
    <%= f.check_box :windscreen_repair %>
  </div>
  <div class="field">
    <%= f.label :windscreen_cost %><br>
    <%= f.check_box :windscreen_cost %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Online_insurance_underwriter/app/views/policies/edit.html.erb
<h1>Editing policy</h1>

<%= render 'form' %>

<%= link_to 'Show', @policy %> |
<%= link_to 'Back', policies_path %>

Online_insurance_underwriter/app/views/policies/index.html.erb
<h1>Listing policies</h1>

<table>
  <thead>
    <tr>
      <th>Policy excess</th>
      <th>Breakdown cover</th>
      <th>Windscreen repair</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @policies.each do |policy| %>
      <tr>
        <td><%= policy.policy_excess %></td>
        <td><%= policy.breakdown_cover %></td>
        <td><%= policy.windscreen_repair %></td>
        <td><%= policy.windscreen_cost %></td>
        <td><%= link_to 'Show', policy %></td>
        <td><%= link_to 'Edit', edit_policy_path(policy) %></td>
        <td><%= link_to 'Destroy', policy, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Policy', new_policy_path %>

Online_insurance_underwriter/app/views/policies/new.html.erb
<h1>New policy</h1>

<%= render 'form' %>

<%= link_to 'Back', policies_path %>

Online_insurance_underwriter/app/views/policies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Policy excess:</strong>
  <%= @policy.policy_excess %>
</p>

<p>
  <strong>Breakdown cover:</strong>
  <%= @policy.breakdown_cover %>
</p>

<p>
  <strong>Windscreen repair:</strong>
  <%= @policy.windscreen_repair %>
</p>

<p>
  <strong>Windscreen cost:</strong>
  <%= @policy.windscreen_cost %>
</p>

<%= link_to 'Edit', edit_policy_path(@policy) %> |
<%= link_to 'Back', policies_path %>